### ISSUE TITLE
Field access to path, pathparts and tag - using groupBy

### ISSUE THREAD

**Issue by logscape** [liquidlabsio/fluidity#53]
Analytics need access to the path to use meta-information for processing

Work items:
1. introduce path field
2. provide field access to analytics (as parameter?) - normally needs along with regular processing. i.e. group-by-path-path[1] to extract serverless function name or region?
3.  update or add new analytic that supports groupBy or concatenation functionality.
**i.e.** 
* analytic.countEach(field) groupBy(_meta.path[2])
* analytic.stats(field-mem-use) groupBy(_meta.path[1])

**Comment by bluemonk3y** [comment]
fixed
